# Generated by Django 4.2.5 on 2024-08-06 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('valeur', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Degret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degret', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SinfInd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sinf', models.IntegerField()),
                ('numind', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val', models.IntegerField()),
                ('degret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.degret')),
                ('sinf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.sinfind')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('administration', models.ManyToManyField(to='api.administration')),
            ],
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slairebase', models.IntegerField()),
                ('primeAdministration', models.IntegerField(default=0)),
                ('primeAutre', models.IntegerField(default=0)),
                ('salairefinale', models.IntegerField(default=0)),
                ('administration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.administration')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.section')),
                ('sinf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sinfind')),
                ('valeuridentifiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.table')),
            ],
        ),
    ]
