# Generated by Django 4.2.5 on 2024-08-07 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poste',
            name='name',
        ),
        migrations.RemoveField(
            model_name='poste',
            name='sinf',
        ),
        migrations.AddField(
            model_name='poste',
            name='degret',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.degret'),
        ),
        migrations.CreateModel(
            name='Postedispo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameposte', models.CharField(max_length=200)),
                ('sinf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sinfind')),
            ],
        ),
    ]
