# Generated by Django 4.2.5 on 2024-08-07 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_poste_name_remove_poste_sinf_poste_degret_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poste',
            name='poste',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.postedispo'),
        ),
    ]
