# Generated by Django 4.2.5 on 2024-08-07 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_poste_poste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poste',
            name='valeuridentifiant',
        ),
    ]
