# Generated by Django 4.2.5 on 2024-08-07 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_poste_valeuridentifiant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poste',
            name='administration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.administration'),
        ),
        migrations.AlterField(
            model_name='poste',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.section'),
        ),
    ]
