# Generated by Django 4.2.5 on 2024-08-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_poste_administration_alter_poste_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinfind',
            name='sinf',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
